context.objects = [
    {
        factory = adapter
        args = {
            factory.name = support.null-audio-sink
            node.name = maton-fallback
            node.description = "MatonOS fallback audio"
            media.class = Audio/Sink
            audio.position = [ FL FR ]
            priority.session = 1
            object.linger = true
        }
    }
]
