#!/usr/bin/env python3
"""Generate a forwarding library source for the Xwayland EGL shim.

Usage: gen_forward.py OUT.c VENDOR_LIB REGEX [--skip name,...] HEADER...

Every function declared in the headers whose name matches REGEX becomes an
exported x86_64 trampoline that jumps to the same symbol in VENDOR_LIB,
which is loaded through Android's same-process-HAL namespace when the
library loads (sphal.c). Names in --skip are implemented by hand. Only the
names are taken from the headers, so prototypes never need restating.
"""
import re
import sys

out, vendor, pattern = sys.argv[1:4]
args = sys.argv[4:]
skip = set()
if args and args[0] == "--skip":
    skip = set(filter(None, args[1].split(",")))
    args = args[2:]
name_re = re.compile(pattern)
names = []
for header in args:
    text = open(header).read()
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    # Declarations end in ");" and the function name is the identifier
    # right before the parameter list's opening parenthesis.
    for decl in re.findall(r"[A-Za-z_][^;{}#]*?\([^;{}]*\)\s*;", text):
        m = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*\(", decl)
        if not m:
            continue
        name = m.group(1)
        if "typedef" in decl or "(*" in decl[: m.start() + 2]:
            continue
        if name_re.fullmatch(name) and name not in skip and name not in names:
            names.append(name)

with open(out, "w") as f:
    f.write("/* Generated by gen_forward.py; do not edit. */\n")
    f.write("#include \"sphal.h\"\n\n")
    f.write("static const char* const k_names[] = {\n")
    for n in names:
        f.write(f'  "{n}",\n')
    f.write("};\n")
    f.write(f"__attribute__((visibility(\"hidden\"))) void* maton_forward_table[{len(names)}];\n\n")
    for i, n in enumerate(names):
        f.write(f'__asm__(".globl {n}\\n.type {n},@function\\n{n}:\\n'
                f'  jmp *maton_forward_table+{8 * i}(%rip)\\n");\n')
    f.write("\n__attribute__((constructor)) static void resolve(void) {\n")
    f.write(f'  maton_sphal_resolve("{vendor}", k_names, maton_forward_table, {len(names)});\n')
    f.write("}\n")
print(f"{out}: {len(names)} functions forwarded to {vendor}", file=sys.stderr)
