import { getLocales } from "expo-localization";

const en = {
  app: "MatonOS",
  settings: "Settings",
  install: "Install MatonOS",
  sleep: "Sleep",
  hardware: "Hardware",
  developer: "Developer",
  about: "About",
  back: "Back",
  powerIdle: "Power and idle behavior",
  hardwareSummary: "Hardware detected by MatonOS",
  developerSummary: "Review application trust and capabilities",
  aboutSummary: "Build and device information",
  installSummary: "Install MatonOS to a separate drive",
  installLiveOnly: "Installation is available only in the live image.",
  unknown: "Unknown",
  unavailable: "Unavailable",
  connected: "Connected",
  available: "Available",
  notDetected: "Not detected",
  sleepService: "Sleep service",
  service: "Service",
  systemState: "System state",
  awake: "Awake",
  sleeping: "Sleeping",
  suspendSupport: "Suspend support",
  ownsIdle: "Owns system idle suspend on this PC.",
  idleTimeout: "Idle timeout",
  sleepWhenIdle: "Sleep when idle",
  keepAwake: "Turn off to keep the PC awake.",
  never: "Never",
  minutes: "minutes",
  applyTimeout: "Apply timeout",
  sleepMode: "Sleep mode",
  automatic: "Automatic",
  automaticDescription: "Use the platform's recommended suspend mode.",
  suspend: "Suspend",
  suspendDescription: "Keep memory powered for a quick resume.",
  hibernate: "Hibernate",
  hibernateDescription: "Save the session to disk, then power off.",
  refresh: "Refresh",
  refreshStatus: "Refresh status",
  refreshHardware: "Refresh hardware",
  installProfile: "Install profile",
  minimumDrive: "Minimum drive",
  slotPlan: "Slot plan",
  slotLabels: "A then B",
  slotDescription: "Copies the live system to A, then clones A to B.",
  abNotIncluded:
    "Selected media files are staged during install and imported after the first boot.",
  availableDrives: "Available drives",
  capacity: "Capacity",
  connection: "Connection",
  selected: "Selected",
  selectDrive: "Select drive",
  noSafeDrives: "No safe target drives were reported.",
  eraseConfirmation: "Erase confirmation",
  eraseWarning: "All data on {model} ({size}) will be erased.",
  reviewTarget: "Review the target carefully before continuing.",
  reviewPlan: "Review install plan",
  goBack: "Go back",
  confirmInstall: "Confirm erase and install",
  startingInstall: "Starting install",
  installSuccess:
    "Every requested operation reported success. Verify the target before rebooting.",
  installUnavailable:
    "Install stays disabled until dry-run and target-disk readback verification pass.",
  installProfileHeading: "Install MatonOS to a separate drive",
  battery: "Battery",
  status: "Status",
  power: "Power",
  connectedToPower: "Connected to power",
  batteryOrDesktop: "Battery or desktop power",
  wireless: "Wireless",
  wifi: "Wi-Fi",
  bluetooth: "Bluetooth",
  physicalAdapter: "Physical adapter",
  virtualRadio: "Virtual radio",
  physicalController: "Physical controller",
  virtualController: "Virtual controller",
  audioGraphics: "Audio and graphics",
  audioOutput: "Audio output",
  graphicsRenderer: "Graphics renderer",
  software: "Software",
  hardwareRenderer: "Hardware",
  camera: "Camera",
  connectedCameras: "Connected cameras",
  trustedApps: "Trusted developer apps",
  trustedAppsDescription:
    "Review which apps can use MatonOS bridge capabilities.",
  trustedAppsDetails:
    "Trust is granted per app and per capability. Built-in MatonOS apps are pre-authorized; other apps require your approval.",
  openTrustedApps: "Open trusted apps",
  osVersion: "OS version",
  build: "Build",
  device: "Device",
  sdkLevel: "SDK level",
  basedOnAosp: "MatonOS is based on AOSP and built for generic x86_64 PCs.",
  timeoutServiceUnavailable: "Sleep service is unavailable.",
  unreadableSleepState: "Sleep service returned an unreadable state.",
  installServiceUnavailable: "Install service is unavailable.",
  settingApplied: "Setting applied.",
  sleepControlUnavailable: "Sleep control is unavailable.",
  invalidTarget: "Cannot prepare this target.",
  installFailed: "Install operation failed.",
};

type Copy = typeof en;
const translations: Record<string, Copy> = { en };
const locale = getLocales()[0]?.languageTag ?? "en";
const language = locale.split("-")[0]?.toLowerCase() ?? "en";

export const copy: Copy = translations[language] ?? en;
export const numberFormat = new Intl.NumberFormat(locale, {
  maximumFractionDigits: 1,
});
