#!/usr/bin/env bash
# Build every registered MatonOS Gradle app outside Soong. Each APK is signed
# with its own user-local development key and staged in prebuilt/apps-built/.
set -Eeuo pipefail

die() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }
DEVICE_DIR=$(dirname "$(dirname "$(readlink -f "$0")")")
AOSP=$(readlink -f "$DEVICE_DIR/../../..")
SDK=${MATON_ANDROID_SDK:-$HOME/Documents/matonos-android-sdk}
SDK_TOOLS_REV=15859902
SDK_TOOLS_SHA=4e4c464f145a7512b57d088ac6c278c03c9eea610886b35a5e0804e74eedf583
GRADLE_HOME=${MATON_GRADLE_HOME:-$HOME/Documents/gradle-9.4.1}
KEY_DIR=${MATON_KEY_DIR:-$HOME/.config/matonos-keys}
KEY_ALIAS=matonos-dev
APP_JOBS=${MATON_BUILD_JOBS:-4}
APP_LIST=$DEVICE_DIR/buildinfra/apps/apps.list
JAVA_HOME=${JAVA_HOME:-$AOSP/prebuilts/jdk/jdk21/linux-x86}
if [[ -x $JAVA_HOME/bin/java ]]; then export JAVA_HOME PATH="$JAVA_HOME/bin:$PATH"; fi

for tool in java keytool curl unzip openssl sha256sum; do
  command -v "$tool" >/dev/null || die "$tool is required"
done
[[ $APP_JOBS =~ ^[1-4]$ ]] || die "MATON_BUILD_JOBS must be between 1 and 4"
for api in 35 36; do
  [[ -f $AOSP/prebuilts/sdk/$api/public/android.jar ]] || die "AOSP API $api public SDK stubs are missing"
done
[[ -s $APP_LIST ]] || die "no app registry at $APP_LIST"

# Use a user-local SDK. SDK Manager supplies the complete Android platform
# package metadata/resources; the public android.jar is replaced with AOSP's
# matching API stubs for this checkout.
mkdir -p "$SDK/cmdline-tools" "$SDK/platforms" "$SDK/build-tools"
SDKMANAGER=$SDK/cmdline-tools/latest/bin/sdkmanager
if [[ ! -x $SDKMANAGER ]]; then
  tmp=$(mktemp -d "$SDK/.cmdline-tools.XXXXXX")
  trap 'rm -rf "$tmp"' EXIT
  curl -fsSL "https://dl.google.com/android/repository/commandlinetools-linux-${SDK_TOOLS_REV}_latest.zip" -o "$tmp/tools.zip"
  echo "$SDK_TOOLS_SHA  $tmp/tools.zip" | sha256sum -c - >/dev/null || die "Android command-line tools checksum mismatch"
  mkdir -p "$tmp/extract"
  unzip -q "$tmp/tools.zip" -d "$tmp/extract"
  mv "$tmp/extract/cmdline-tools" "$SDK/cmdline-tools/latest"
  rm -rf "$tmp"
  trap - EXIT
fi
for api in 35 36; do
if [[ -d $SDK/platforms/android-$api &&
      ( ! -f $SDK/platforms/android-$api/build.prop || ! -d $SDK/platforms/android-$api/data/res ) ]]; then
  python3 - "$SDK/platforms/android-$api" <<'PY_CLEAN'
import pathlib, shutil, sys
p = pathlib.Path(sys.argv[1])
if p.is_dir(): shutil.rmtree(p)
PY_CLEAN
fi
done
if [[ ! -f $SDK/platforms/android-35/build.prop || ! -f $SDK/platforms/android-36/build.prop ||
      ! -x $SDK/build-tools/36.0.0/zipalign || ! -x $SDK/build-tools/36.0.0/apksigner ]]; then
  set +o pipefail
  yes | "$SDKMANAGER" --sdk_root="$SDK" --licenses >/dev/null
  sdkmanager_status=${PIPESTATUS[1]}
  set -o pipefail
  (( sdkmanager_status == 0 )) || die "SDK license acceptance failed"
  "$SDKMANAGER" --sdk_root="$SDK" --install 'platforms;android-35' 'platforms;android-36' 'build-tools;36.0.0' >/dev/null
fi
for api in 35 36; do cp "$AOSP/prebuilts/sdk/$api/public/android.jar" "$SDK/platforms/android-$api/android.jar"; done

if [[ -x $GRADLE_HOME/bin/gradle ]]; then
  GRADLE=$GRADLE_HOME/bin/gradle
  [[ $($GRADLE --version | sed -n 's/^Gradle //p' | head -n1) == 9.4.1 ]] || die "$GRADLE is not Gradle 9.4.1"
else
  GRADLE=
fi

mkdir -p "$KEY_DIR" "$DEVICE_DIR/prebuilt/apps-built" "$DEVICE_DIR/buildinfra/apps-built"
chmod 700 "$KEY_DIR"
allow_tmp=$(mktemp)
cert_tmp=$(mktemp)
trap 'rm -f "$allow_tmp" "$cert_tmp"' EXIT
printf '# Generated by tools/build-apps.sh; key-id and SHA-256 for each registered app certificate.\n' > "$allow_tmp"

# Fingerprint of an app's build inputs (sources, lock files, native modules,
# shared libraries, signing cert, this script). Unchanged fingerprint + staged
# APK -> skip npm/prebuild/Gradle. MATON_APPS_FORCE=1 rebuilds everything.
inputs_hash() {
  local d
  {
    for d in "$@"; do
      [[ -d $d ]] || continue
      (cd "$d" && find . \( -path ./android -o -path ./node_modules -o -name node_modules \
          -o -name build -o -name .gradle -o -name .cxx -o -name '.metro*' \
          -o -name framework-stubs.jar -o -name '.attach_pid*' \) -prune -o -type f -print0 |
        LC_ALL=C sort -z | xargs -0 -r sha256sum)
    done
    sha256sum "$0"
    node --version 2>/dev/null
  } | sha256sum | cut -d' ' -f1
}

while IFS=$'\t' read -r key_id project_rel task apk_name; do
  [[ -n $key_id && $key_id != \#* ]] || continue
  [[ -n $project_rel && -n $task && -n $apk_name ]] || die "bad app registry row: $key_id"
  [[ $key_id =~ ^[a-z0-9][a-z0-9_-]*$ && $apk_name =~ ^[A-Za-z0-9._-]+\.apk$ ]] || die "unsafe app registry row: $key_id"
  # MATON_APPS_ONLY="id ...": build only these apps (others keep their staged APKs).
  if [[ -n ${MATON_APPS_ONLY:-} && " ${MATON_APPS_ONLY} " != *" $key_id "* ]]; then continue; fi
  # MATON_SKIP_APPS="id ...": keep the already-staged APK (e.g. an app mid-rewrite).
  if [[ " ${MATON_SKIP_APPS:-} " == *" $key_id "* ]]; then info "Skipping $key_id (MATON_SKIP_APPS), keeping staged $apk_name"; continue; fi
  project=$DEVICE_DIR/$project_rel
  # Expo projects (task column "expo"): android/ is generated by expo prebuild
  # (CNG) and built with its own Gradle wrapper, not the pinned Gradle.
  expo=0
  if [[ $task == expo ]]; then
    expo=1 task=:app:assembleRelease
    [[ -f $project/package-lock.json ]] || die "no package-lock.json in $project"
  fi
  [[ $expo == 1 ]] || [[ -f $project/settings.gradle || -f $project/settings.gradle.kts ]] || die "no Gradle settings in $project"
  [[ $expo == 1 || -x $GRADLE || -x $project/gradlew ]] || die "no pinned Gradle executable for $project"
  key_file=$KEY_DIR/$key_id.jks
  password_file=$KEY_DIR/$key_id.pass
  if [[ ! -s $key_file ]]; then
    umask 077
    openssl rand -hex 24 > "$password_file"
    keypass=$(cat "$password_file")
    keytool -genkeypair -noprompt -keystore "$key_file" -storetype JKS \
      -storepass "$keypass" -keypass "$keypass" -alias "$KEY_ALIAS" \
      -keyalg RSA -keysize 3072 -validity 10000 \
      -dname "CN=MatonOS $key_id development key, O=MatonOS"
  fi
  [[ -s $password_file ]] || die "missing development key password: $password_file"
  keypass=$(cat "$password_file")
  keytool -exportcert -rfc -keystore "$key_file" -storepass "$keypass" \
    -alias "$KEY_ALIAS" -file "$cert_tmp" >/dev/null 2>&1
  cert_sha=$(openssl x509 -in "$cert_tmp" -outform DER | sha256sum | awk '{print $1}')
  printf '%s %s\n' "$key_id" "$cert_sha" >> "$allow_tmp"

  stamp=$DEVICE_DIR/prebuilt/apps-built/.$key_id.inputs
  fingerprint=$(inputs_hash "$project" "$DEVICE_DIR/rn-apps/rn-common" "$DEVICE_DIR/buildinfra/client")-$cert_sha
  if [[ ${MATON_APPS_FORCE:-0} != 1 && -s $stamp && $(cat "$stamp") == "$fingerprint" &&
        -s $DEVICE_DIR/prebuilt/apps-built/$apk_name && -s $DEVICE_DIR/buildinfra/apps-built/$apk_name ]]; then
    info "Skipping $key_id: inputs unchanged since the staged $apk_name"
    continue
  fi
  if [[ $expo == 1 ]]; then
    info "Preparing Expo project $key_id (npm ci, expo prebuild)"
    (cd "$project" && npm ci --ignore-scripts --no-audit --no-fund) || die "npm ci failed for $key_id"
  fi

  # Optional hidden/system API fallback. The jar is compile-only and excluded
  # from APK packaging. Public APIs and the bridge remain the preferred path.
  framework_stub=${MATON_FRAMEWORK_STUB_JAR:-$AOSP/out/target/product/pc_x86_64/system/framework/framework.jar}
  module_dir=$project/app
  if [[ $expo == 1 ]]; then module_dir=; fi
  if [[ -f $framework_stub && -d $module_dir ]]; then
    mkdir -p "$module_dir/libs"
    cp "$framework_stub" "$module_dir/libs/framework-stubs.jar"
    framework_stub=$module_dir/libs/framework-stubs.jar
  else
    framework_stub=
  fi

  if [[ $expo == 1 ]]; then info "Building $key_id with the Expo project's pinned Gradle wrapper"
  else info "Building $key_id ($project_rel) with Gradle 9.4.1 / AGP 9.2.0"; fi
  (
    cd "$project"
    export ANDROID_HOME=$SDK ANDROID_SDK_ROOT=$SDK
    export MATON_SIGNING_STORE_FILE=$key_file MATON_SIGNING_STORE_PASSWORD=$keypass
    export MATON_SIGNING_KEY_ALIAS=$KEY_ALIAS MATON_SIGNING_KEY_PASSWORD=$keypass
    export MATON_FRAMEWORK_STUB_JAR=$framework_stub
    if [[ $expo == 1 ]]; then
      CI=1 npx expo prebuild --platform android --clean --no-install
      [[ -x android/gradlew ]] || die "Expo prebuild did not generate android/gradlew for $key_id"
      ./android/gradlew -p android --no-daemon --max-workers "$APP_JOBS" --stacktrace "$task"
    elif [[ -n $GRADLE ]]; then "$GRADLE" --no-daemon --max-workers "$APP_JOBS" --stacktrace "$task"
    else "$project/gradlew" --no-daemon --max-workers "$APP_JOBS" --stacktrace "$task"
    fi
  )
  apk_root=$project; if [[ $expo == 1 ]]; then apk_root=$project/android/app; fi
  apk=$(find "$apk_root" -type f -path '*/build/outputs/apk/release/*.apk' -print -quit)
  [[ -n $apk && -s $apk ]] || die "Gradle did not produce a release APK for $key_id"
  if [[ $expo == 1 ]]; then
    (cd "$project" && npm run check:release-linkage) || die "release linkage check failed for $key_id"
    app_id=${key_id#matonos-}
    permission_xml=$project/android/app/src/main/assets/privapp-permissions-org.matonos.$app_id.xml
    [[ -s $permission_xml ]] || permission_xml=$project/privapp-permissions-org.matonos.$app_id.xml
    [[ -s $permission_xml ]] || die "Expo project did not generate its privileged permission XML: $key_id"
    install -m 0644 "$permission_xml" "$DEVICE_DIR/buildinfra/privapp-permissions/privapp-permissions-org.matonos.$app_id.xml"
  fi
  apk_cert=$($SDK/build-tools/36.0.0/apksigner verify --print-certs "$apk" \
    | sed -n 's/^Signer #1 certificate SHA-256 digest: //p' | tr '[:upper:]' '[:lower:]' | head -n1)
  [[ -n $apk_cert && $apk_cert == "$cert_sha" ]] || die "APK signer does not match persistent key for $key_id"
  cp "$apk" "$DEVICE_DIR/prebuilt/apps-built/$apk_name"
  cp "$apk" "$DEVICE_DIR/buildinfra/apps-built/$apk_name"
  info "Staged $DEVICE_DIR/prebuilt/apps-built/$apk_name (certificate SHA-256 $cert_sha)"
  printf '%s\n' "$fingerprint" > "$stamp"
done < "$APP_LIST"

install -m 0644 "$allow_tmp" "$DEVICE_DIR/systembridge/res/raw/caller_cert_allowlist.txt"
info "Updated System Bridge certificate allowlist"
