#!/usr/bin/env bash
# make-payload.sh — package an AOSP PC build into an installer payload.
#
# Usage:
#   ./make-payload.sh -o <aosp product out dir> -k <bzImage> [-b <systemd-bootx64.efi>]
#                     [-s <super partition bytes>] [-c "<kernel cmdline>"] [-d <payload dir>]
#
# Example:
#   ./make-payload.sh -o ~/aosp/out/target/product/pc_x86_64 \
#                     -k ~/linux/arch/x86/boot/bzImage
#
# Produces <payload dir>/ containing:
#   bzImage, ramdisk.img, [vendor_ramdisk.img], super.img.zst,
#   efi/systemd-bootx64.efi, payload.conf, SHA256SUMS
set -Eeuo pipefail

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

OUT=""
KERNEL=""
BOOTEFI="/usr/lib/systemd/boot/efi/systemd-bootx64.efi"
SUPER_SIZE_BYTES=8589934592          # must equal BOARD_SUPER_PARTITION_SIZE
CMDLINE="console=tty0 quiet firmware_class.path=/vendor/firmware androidboot.hardware=pc_x86_64 androidboot.selinux=permissive androidboot.verifiedbootstate=orange"
PAYLOAD="./payload"

while getopts "o:k:b:s:c:d:h" opt; do
  case $opt in
    o) OUT=$OPTARG ;;
    k) KERNEL=$OPTARG ;;
    b) BOOTEFI=$OPTARG ;;
    s) SUPER_SIZE_BYTES=$OPTARG ;;
    c) CMDLINE=$OPTARG ;;
    d) PAYLOAD=$OPTARG ;;
    *) sed -n '2,15p' "$0"; exit 1 ;;
  esac
done

[[ -d $OUT ]]     || die "product out dir not found (-o)"
[[ -f $KERNEL ]]  || die "kernel bzImage not found (-k)"
[[ -f $BOOTEFI ]] || die "systemd-boot EFI binary not found (-b); on Debian/Ubuntu install systemd-boot-efi"
[[ -f $OUT/super.img ]]   || die "$OUT/super.img missing (set BOARD_BUILD_SUPER_IMAGE_BY_DEFAULT := true)"
[[ -f $OUT/ramdisk.img ]] || die "$OUT/ramdisk.img missing"
(( SUPER_SIZE_BYTES % 1048576 == 0 )) || die "super size must be a multiple of 1 MiB"
for t in zstd sha256sum od; do command -v "$t" >/dev/null || die "missing tool: $t"; done

rm -rf "$PAYLOAD"
mkdir -p "$PAYLOAD/efi"

info "Copying kernel, ramdisks and bootloader"
cp "$KERNEL" "$PAYLOAD/bzImage"
cp "$OUT/ramdisk.img" "$PAYLOAD/ramdisk.img"
[[ -f $OUT/vendor_ramdisk.img ]] && cp "$OUT/vendor_ramdisk.img" "$PAYLOAD/vendor_ramdisk.img"
cp "$BOOTEFI" "$PAYLOAD/efi/systemd-bootx64.efi"

# super.img may be an Android sparse image; the installer needs raw bytes.
tmp_raw=$(mktemp --tmpdir super.raw.XXXXXX)
trap 'rm -f "$tmp_raw"' EXIT
magic=$(od -An -tx1 -N4 "$OUT/super.img" | tr -d ' \n')
if [[ $magic == "3aff26ed" ]]; then
  command -v simg2img >/dev/null || die "super.img is sparse; put AOSP's out/host/linux-x86/bin on PATH for simg2img"
  info "Converting sparse super.img to raw"
  simg2img "$OUT/super.img" "$tmp_raw"
else
  cp "$OUT/super.img" "$tmp_raw"
fi

raw_size=$(stat -c %s "$tmp_raw")
[[ $raw_size -eq $SUPER_SIZE_BYTES ]] ||
  die "raw super.img is $raw_size bytes but super size is $SUPER_SIZE_BYTES; they must match BOARD_SUPER_PARTITION_SIZE"

info "Hashing and compressing super.img (zstd -19, may take a while)"
super_sha=$(sha256sum "$tmp_raw" | cut -d' ' -f1)
zstd -19 -T0 -q "$tmp_raw" -o "$PAYLOAD/super.img.zst"

cat > "$PAYLOAD/payload.conf" <<EOF
# Generated by make-payload.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
SUPER_SIZE_BYTES=$SUPER_SIZE_BYTES
SUPER_SHA256=$super_sha
ESP_SIZE_MIB=512
MIN_USERDATA_MIB=8192
KERNEL_CMDLINE="$CMDLINE"
DEBUG_CMDLINE="loglevel=7 printk.devkmsg=on"
EOF

info "Writing SHA256SUMS"
sums=$( cd "$PAYLOAD" && find . -type f -printf '%P\n' | sort | xargs sha256sum )
printf '%s\n' "$sums" > "$PAYLOAD/SHA256SUMS"

info "Payload ready in $PAYLOAD:"
ls -lh "$PAYLOAD" "$PAYLOAD/efi"
